const data = [
  {
    blockID: 'hokkaido_tohoku',
    caption: [
      [
        '北海道',
        'マーリン<span class="cross">×</span>富良野',
        '６／<span class="tcy">１３</span> 北海道新聞',
        'hokkaido',
      ],
      [
        '青森県',
        'アビゲイル<span class="nakaguro">・</span>ウィリアムズ<span class="cross">×</span>十和田湖',
        '６／<span class="tcy">１３</span> 東奥日報<span class="nakaguro">・</span>デーリー東北',
        'aomori',
      ],
      [
        '秋田県',
        'ジャック<span class="nakaguro">・</span>ザ<span class="nakaguro">・</span>リッパー<span class="cross">×</span>男鹿のナマハゲ',
        '６／<span class="tcy">１３</span> 秋田魁新報',
        'akita',
      ],
      [
        '岩手',
        '牛若丸＆武蔵坊弁慶<span class="cross">×</span>わんこそば',
        '６／<span class="tcy">１３</span> 岩手日報',
        'iwate',
      ],
      [
        '山形県',
        'アナスタシア<span class="cross">×</span>蔵王樹氷',
        '６／<span class="tcy">１３</span> 山形新聞',
        'yamagata',
      ],
      [
        '宮城県',
        '清少納言<span class="cross">×</span>松島',
        '６／<span class="tcy">１３</span> 河北新報',
        'miyagi',
      ],
      [
        '福島県',
        '燕青<span class="cross">×</span>霧幻峡',
        '６／<span class="tcy">１３</span> 福島民報',
        'fukushima',
      ],
    ],
    img: [
      '/assets/img/slide_0613_g6z3i5ts/s01',
      '/assets/img/slide_0613_g6z3i5ts/s02',
      '/assets/img/slide_0613_g6z3i5ts/s03',
      '/assets/img/slide_0613_g6z3i5ts/s04',
      '/assets/img/slide_0613_g6z3i5ts/s05',
      '/assets/img/slide_0613_g6z3i5ts/s06',
      '/assets/img/slide_0613_g6z3i5ts/s07',
    ],
    voice: [
      '/reward/voice/marlin_x8gaicdu.mp3',
      '/reward/voice/abigail_c3hbi5ws.mp3',
      '/reward/voice/jack_g3mfudvb.mp3',
      '/reward/voice/iwate_q3piuvwz.mp3',
      '/reward/voice/anastasia_v8c6knzx.mp3',
      '/reward/voice/seisyounagon_p2duhw6i.mp3',
      '/reward/voice/ensei_c5x7zaqh.mp3',
    ],
  },
  {
    blockID: 'kanto_koshin',
    caption: [
      [
        '東京都',
        'マシュ・キリエライト<span class="cross">×</span>ＳＨＩＢＵＹＡ ＳＫＹ',
        '５／４ 読売新聞',
        'tokyo01',
      ],
      [
        '茨城県',
        '加藤段蔵<span class="cross">×</span>偕楽園',
        '５／４ 茨城新聞',
        'ibaraki',
      ],
      [
        '栃木県',
        '玄奘三蔵<span class="cross">×</span>華厳の滝',
        '５／４ 下野新聞',
        'tochigi',
      ],
      [
        '群馬県',
        'ベディヴィエール<span class="cross">×</span>尾瀬',
        '５／４ 上毛新聞',
        'gunma',
      ],
      [
        '埼玉県',
        'エレシュキガル<span class="cross">×</span>首都圏外郭放水路',
        '５／４ 埼玉新聞',
        'saitama',
      ],
      [
        '千葉県',
        'ゲオルギウス<span class="cross">×</span>濃溝の滝',
        '５／４ 千葉日報',
        'chiba',
      ],
      [
        '東京都',
        'アルトリア・ペンドラゴン<span class="cross">×</span>東京タワー',
        '５／４ 東京新聞',
        'tokyo02',
      ],
      [
        '神奈川県',
        'レオナルド・ダ・ヴィンチ<span class="cross">×</span>横浜赤レンガ倉庫',
        '５／４ 神奈川新聞',
        'kanagawa',
      ],
      [
        '山梨県',
        'ポール・バニヤン<span class="cross">×</span>逆さ富士',
        '５／４ 山梨日日新聞',
        'yamanashi',
      ],
      [
        '静岡県',
        '葛飾北斎<span class="cross">×</span>富士山南麓',
        '５／４ 静岡新聞',
        'shizuoka',
      ],
      [
        '長野県',
        'キングプロテア<span class="cross">×</span>槍ヶ岳と雲海',
        '５／４ 信濃毎日新聞',
        'nagano',
      ],
    ],
    img: [
      '/assets/img/slide_0504_jzgkaw3b/s01',
      '/assets/img/slide_0504_jzgkaw3b/s02',
      '/assets/img/slide_0504_jzgkaw3b/s03',
      '/assets/img/slide_0504_jzgkaw3b/s04',
      '/assets/img/slide_0504_jzgkaw3b/s05',
      '/assets/img/slide_0504_jzgkaw3b/s06',
      '/assets/img/slide_0504_jzgkaw3b/s07',
      '/assets/img/slide_0504_jzgkaw3b/s08',
      '/assets/img/slide_0504_jzgkaw3b/s09',
      '/assets/img/slide_0504_jzgkaw3b/s10',
      '/assets/img/slide_0504_jzgkaw3b/s11',
    ],
    voice: [
      '/reward/voice/mashukirielight_v80q8dop.mp3',
      '/reward/voice/katoudanzou_pk39wmli.mp3',
      '/reward/voice/sanzou_y238g0s7.mp3',
      '/reward/voice/bedivier_z3s9x4sm.mp3',
      '/reward/voice/ereshkigal_rqst3sat.mp3',
      '/reward/voice/georgios_mq8rq2au.mp3',
      '/reward/voice/arturiapendragon_crzpavqg.mp3',
      '/reward/voice/devinci_ixzbecr0.mp3',
      '/reward/voice/paulbunyan_iv1zy1h4.mp3',
      '/reward/voice/katsushikahokusai_6f1aw4vi.mp3',
      '/reward/voice/kingprotea_cna82o5v.mp3',
    ],
  },
  {
    blockID: 'tokai_hokuriku',
    caption: [
      [
        '新潟県',
        '風魔小太郎<span class="cross">×</span>苗場スキー場',
        '５／<span class="tcy">２５</span> 新潟日報',
        'niigata',
      ],
      [
        '愛知県',
        '森長可<span class="cross">×</span>手筒花火',
        '５／<span class="tcy">２５</span> 中日新聞',
        'aichi',
      ],
      [
        '岐阜県',
        'シャーロック<span class="nakaguro">・</span>ホームズ<span class="cross">×</span>白川郷',
        '５／<span class="tcy">２５</span> 岐阜新聞',
        'gifu',
      ],
      [
        '福井県',
        '虞美人<span class="cross">×</span>東尋坊',
        '５／<span class="tcy">２５</span> 福井新聞',
        'fukui',
      ],
      [
        '富山県',
        'スカサハ＝スカディ<span class="cross">×</span>雪の大谷',
        '５／<span class="tcy">２５</span> 北日本新聞',
        'toyama',
      ],
      [
        '石川県',
        '紅閻魔<span class="cross">×</span>白米千枚田',
        '５／<span class="tcy">２５</span> 北國新聞',
        'ishikawa',
      ],
    ],
    img: [
      '/assets/img/slide_0525_r6dwy7nt/s01',
      '/assets/img/slide_0525_r6dwy7nt/s02',
      '/assets/img/slide_0525_r6dwy7nt/s03',
      '/assets/img/slide_0525_r6dwy7nt/s04',
      '/assets/img/slide_0525_r6dwy7nt/s05',
      '/assets/img/slide_0525_r6dwy7nt/s06',
    ],
    voice: [
      '/reward/voice/fumakotaro_p582tr3s.mp3',
      '/reward/voice/morinagayoshi_w6k2uqsi.mp3',
      '/reward/voice/holmes_z987qyuc.mp3',
      '/reward/voice/gubijin_h8p2nmya.mp3',
      '/reward/voice/scathachskadi_y3jprc5i.mp3',
      '/reward/voice/benienma_u3wf8mvj.mp3',
    ],
  },
  {
    blockID: 'kansai',
    caption: [
      [
        '大阪府',
        'カルナ＆アルジュナ<span class="cross">×</span>通天閣',
        '７／<span class="tcy">２０</span> 朝日新聞、産経新聞',
        'osaka',
      ],
      [
        '三重県',
        'メドゥーサ<span class="cross">×</span>熊野古道',
        '７／<span class="tcy">２０</span> 中日新聞',
        'mie',
      ],
      [
        '京都府',
        '酒呑童子<span class="cross">×</span>小径',
        '７／<span class="tcy">２０</span> 京都新聞',
        'kyoto',
      ],
      [
        '滋賀県',
        '鈴鹿御前<span class="cross">×</span>満月寺',
        '７／<span class="tcy">２０</span> 京都新聞',
        'shiga',
      ],
      [
        '奈良県',
        '柳生但馬守宗矩<span class="cross">×</span>長谷寺本堂',
        '７／<span class="tcy">２０</span> 奈良新聞',
        'nara',
      ],
      [
        '和歌山県',
        '清姫<span class="cross">×</span>道成寺',
        '７／<span class="tcy">２０</span> 朝日新聞、産経新聞',
        'wakayama',
      ],
      [
        '兵庫県',
        '刑部姫<span class="cross">×</span>白鷺城',
        '７／<span class="tcy">２０</span> 神戸新聞',
        'hyogo',
      ],
    ],
    img: [
      '/assets/img/slide_0720_t5sh2mdx/s01',
      '/assets/img/slide_0720_t5sh2mdx/s02',
      '/assets/img/slide_0720_t5sh2mdx/s03',
      '/assets/img/slide_0720_t5sh2mdx/s04',
      '/assets/img/slide_0720_t5sh2mdx/s05',
      '/assets/img/slide_0720_t5sh2mdx/s06',
      '/assets/img/slide_0720_t5sh2mdx/s07',
    ],
    voice: [
      '/reward/voice/osaka_m3pj5yea.mp3',
      '/reward/voice/ana_u2h4ngmj.mp3',
      '/reward/voice/shutendouji_y8nebhik.mp3',
      '/reward/voice/suzukagozen_g6574qny.mp3',
      '/reward/voice/yagyu_r8mqtiwy.mp3',
      '/reward/voice/kiyohime_k823t6nz.mp3',
      '/reward/voice/osakabehime_c6zgtihx.mp3',
    ],
  },
  {
    blockID: 'chugoku_shikoku',
    caption: [
      [
        '岡山県',
        '紫式部<span class="cross">×</span>倉敷美観地区',
        '７／６ 山陽新聞',
        'okayama',
      ],
      [
        '広島県',
        '蘭陵王<span class="cross">×</span>紅葉谷公園',
        '７／６ 中国新聞',
        'hiroshima',
      ],
      [
        '鳥取県',
        'ニトクリス<span class="cross">×</span>鳥取砂丘',
        '７／６ 日本海新聞',
        'tottori',
      ],
      [
        '島根県',
        'クー<span class="nakaguro">・</span>フーリン[オルタ]<span class="cross">×</span>通天橋',
        '７／６ 山陰中央新報',
        'shimane',
      ],
      [
        '山口県',
        '佐々木小次郎<span class="cross">×</span>巌流島',
        '７／６ 山口新聞',
        'yamaguchi',
      ],
      [
        '香川県',
        '宮本武蔵<span class="cross">×</span>道の駅 小豆島オリーブ公園',
        '７／６ 四国新聞',
        'kagawa',
      ],
      [
        '徳島県',
        'アタランテ<span class="cross">×</span>剣山',
        '７／６ 徳島新聞',
        'tokushima',
      ],
      [
        '愛媛県',
        'ジャガーマン<span class="cross">×</span>道後温泉本館',
        '７／６ 愛媛新聞',
        'ehime',
      ],
      [
        '高知県',
        '岡田以蔵<span class="cross">×</span>桂浜',
        '７／６ 高知新聞',
        'ehime',
      ],
    ],
    img: [
      '/assets/img/slide_0706_x2szuqep/s01',
      '/assets/img/slide_0706_x2szuqep/s02',
      '/assets/img/slide_0706_x2szuqep/s03',
      '/assets/img/slide_0706_x2szuqep/s04',
      '/assets/img/slide_0706_x2szuqep/s05',
      '/assets/img/slide_0706_x2szuqep/s06',
      '/assets/img/slide_0706_x2szuqep/s07',
      '/assets/img/slide_0706_x2szuqep/s08',
      '/assets/img/slide_0706_x2szuqep/s09',
    ],
    voice: [
      '/reward/voice/murasakishikibu_p4tmsb3c.mp3',
      '/reward/voice/lanryouou_m9igpr3b.mp3',
      '/reward/voice/nitocris_g9sewnx5.mp3',
      '/reward/voice/cuchulainnalter_p6zqh5wt.mp3',
      '/reward/voice/sasakikojirou_q5tu2ezb.mp3',
      '/reward/voice/miyamotomusashi_j3a4gh9v.mp3',
      '/reward/voice/atalanta_i5zpnwhj.mp3',
      '/reward/voice/jagaman_h3qmx7jv.mp3',
      '/reward/voice/okadaIzou_m6hj9w8r.mp3',
    ],
  },
  {
    blockID: 'kyushu_okinawa',
    caption: [
      [
        '福岡県',
        '謎のヒロインＸ<span class="cross">×</span>中洲屋台街',
        '６／３ 西日本新聞',
        'fukuoka',
      ],
      [
        '佐賀県',
        'イシュタル<span class="cross">×</span>嘉瀬川河川敷',
        '６／３ 佐賀新聞',
        'saga',
      ],
      [
        '長崎県',
        'マリー<span class="nakaguro">・</span>アントワネット<span class="cross">×</span>ハウステンボス',
        '６／３ 長崎新聞',
        'nagasaki',
      ],
      [
        '熊本県',
        '天草四郎<span class="cross">×</span>阿蘇カルデラ',
        '６／３ 熊本日日新聞',
        'kumamoto',
      ],
      [
        '大分県',
        'フランケンシュタイン<span class="cross">×</span>沈堕発電所跡',
        '６／３ 大分合同新聞',
        'oita',
      ],
      [
        '宮崎県',
        'シグルド＆ブリュンヒルデ<span class="cross">×</span>都井岬',
        '６／３ 宮崎日日新聞',
        'miyazaki',
      ],
      [
        '鹿児島県',
        'ヘラクレス<span class="cross">×</span>屋久島',
        '６／３ 南日本新聞',
        'kagoshima',
      ],
      [
        '沖縄県',
        'マルタ<span class="cross">×</span>石垣島',
        '６／３ 沖縄タイムス<span class="nakaguro">・</span>琉球新報',
        'okinawa',
      ],
    ],
    img: [
      '/assets/img/slide_0603_d486tjek/s01',
      '/assets/img/slide_0603_d486tjek/s02',
      '/assets/img/slide_0603_d486tjek/s03',
      '/assets/img/slide_0603_d486tjek/s04',
      '/assets/img/slide_0603_d486tjek/s05',
      '/assets/img/slide_0603_d486tjek/s06',
      '/assets/img/slide_0603_d486tjek/s07',
      '/assets/img/slide_0603_d486tjek/s08',
    ],
    voice: [
      '/reward/voice/nazonohiroinx_f7z9tqkr.mp3',
      '/reward/voice/ishtar_a4y58gn7.mp3',
      '/reward/voice/marieantoinette_s27hmtyp.mp3',
      '/reward/voice/amakusa_q79zyb2t.mp3',
      '/reward/voice/frankenstein_y827gbqm.mp3',
      '/reward/voice/miyazaki_f2qcmwrh.mp3',
      '/reward/voice/hercules_r5jdn9xv.mp3',
      '/reward/voice/martha_g9y3tjq4.mp3',
    ],
  },
];

const archiveData = [
  {
    id: 'hokkaido',
    pref: '北海道',
    servant: 'マーリン',
    cv: '櫻井孝宏',
    copy: '「素敵な花畑じゃないか！ところで美しいご婦人はどこに？」',
    spot: '富良野',
    illust: 'タイキ',
    media: '6/13 北海道新聞',
    hash: 'x8gaicdu',
    update: '2020/6/13',
    position: [-100, -400],
  },
  {
    id: 'aomori',
    pref: '青森県',
    servant: 'アビゲイル・ウィリアムズ',
    cv: '大和田仁美',
    copy: '「マスター、手をかしてくださらない？」',
    spot: '十和田湖',
    illust: '黒星紅白',
    media: '6/13 東奥日報、デーリー東北',
    hash: 'c3hbi5ws',
    update: '2020/6/13',
    position: [-200, -400],
  },
  {
    id: 'iwate',
    pref: '岩手県',
    servant: '牛若丸＆武蔵坊弁慶',
    cv: '早見沙織＆稲田徹',
    copy:
      '「どうした武蔵坊、ペースが落ちているのではないか？」<br>「むぅん！まだまだ！」',
    spot: 'わんこそば',
    illust: '真じろう、坂本みねぢ',
    media: '6/13 岩手日報',
    hash: 'q3piuvwz',
    update: '2020/6/13',
    position: [-300, -400],
  },
  {
    id: 'miyagi',
    pref: '宮城県',
    servant: '清少納言',
    cv: 'ファイルーズあい',
    copy: '「ちゃんマスー！とりま撮っとく？」',
    spot: '松島',
    illust: 'Mika Pikazo',
    media: '6/13 河北新報',
    hash: 'p2duhw6i',
    update: '2020/6/13',
    position: [-400, -400],
  },
  {
    id: 'akita',
    pref: '秋田県',
    servant: 'ジャック・ザ・リッパー',
    cv: '丹下桜',
    copy: '「おかあさんは、いないかー！！」',
    spot: '男鹿のナマハゲ',
    illust: '近衛乙嗣',
    media: '6/13 秋田魁新報',
    hash: 'g3mfudvb',
    update: '2020/6/13',
    position: [-500, -400],
  },
  {
    id: 'yamagata',
    pref: '山形県',
    servant: 'アナスタシア',
    cv: '原由実',
    copy: '「あら、その程度？ロシアの冬は、もっと厳しいのだけれど」',
    spot: '蔵王樹氷',
    illust: 'sime',
    media: '6/13 山形新聞',
    hash: 'v8c6knzx',
    update: '2020/6/13',
    position: [0, -500],
  },
  {
    id: 'fukushima',
    pref: '福島県',
    servant: '燕青',
    cv: '岡本信彦',
    copy:
      '「夢幻の渡しと言うのなら、この拳舞、主人（マスター）の夢に捧げよう」',
    spot: '霧幻峡',
    illust: '縞うどん（TYPE-MOON）',
    media: '6/13 福島民報',
    hash: 'c5x7zaqh',
    update: '2020/6/13',
    position: [-100, -500],
  },
  {
    id: 'ibaraki',
    pref: '茨城県',
    servant: '加藤段蔵',
    cv: '明坂聡美',
    copy: '「これは・・・！まさに幻術要らずでございます」',
    spot: '偕楽園',
    illust: '曽我誠',
    media: '5/4 茨城新聞',
    hash: 'pk39wmli',
    update: '2020/5/4',
    position: [0, 0],
  },
  {
    id: 'tochigi',
    pref: '栃木県',
    servant: '玄奘三蔵',
    cv: '小松未可子',
    copy: '「華厳だなんて、うんうん、ありがたい滝ね！」',
    spot: '華厳の滝',
    illust: '岡崎武士',
    media: '5/4 下野新聞',
    hash: 'y238g0s7',
    update: '2020/5/4',
    position: [-100, 0],
  },
  {
    id: 'gunma',
    pref: '群馬県',
    servant: 'ベディヴィエール',
    cv: '宮野真守',
    copy: '「ふふ。これほど穏やかで楽しい道は、そうないかと」',
    spot: '尾瀬',
    illust: '天空すふぃあ',
    media: '5/4 上毛新聞',
    hash: 'z3s9x4sm',
    update: '2020/5/4',
    position: [-200, 0],
  },
  {
    id: 'saitama',
    pref: '埼玉県',
    servant: 'エレシュキガル',
    cv: '植田佳奈',
    copy: '「現世の地下も、中々のものなのだわ！」',
    spot: '首都圏外郭放水路',
    illust: '森井しづき',
    media: '5/4 埼玉新聞',
    hash: 'rqst3sat',
    update: '2020/5/4',
    position: [-300, 0],
  },
  {
    id: 'chiba',
    pref: '千葉県',
    servant: 'ゲオルギウス',
    cv: '西前忠久',
    copy: '「心が落ち着きます。ここには善い光がある」',
    spot: '濃溝の滝',
    illust: '中央東口',
    media: '5/4 千葉日報',
    hash: 'mq8rq2au',
    update: '2020/5/4',
    position: [-400, 0],
  },
  {
    id: 'tokyo01',
    pref: '東京都',
    servant: 'マシュ・<br>キリエライト',
    cv: '高橋李依',
    copy: '「あぁ、まるで地上の星空のようです！」',
    spot: 'SHIBUYA SKY',
    illust: '武内崇',
    media: '5/4 読売新聞',
    hash: 'v80q8dop',
    update: '2020/5/4',
    position: [-500, 0],
  },
  {
    id: 'tokyo02',
    pref: '東京都',
    servant: 'アルトリア・<br>ペンドラゴン',
    cv: '川澄綾子',
    copy: '「眠らぬ街の人々に、尊敬と、祝福を」',
    spot: '東京タワー',
    illust: '武内崇',
    media: '5/4 東京新聞',
    hash: 'crzpavqg',
    update: '2020/5/4',
    position: [0, -100],
  },
  {
    id: 'kanagawa',
    pref: '神奈川県',
    servant: 'レオナルド・<br>ダ・ヴィンチ',
    cv: '坂本真綾',
    copy: '「いいね、趣きバッチリ！フィレンツェみたい！」',
    spot: '横浜赤レンガ倉庫',
    illust: '下越（TYPE-MOON）',
    media: '5/4 神奈川新聞',
    hash: 'ixzbecr0',
    update: '2020/5/4',
    position: [-100, -100],
  },
  {
    id: 'yamanashi',
    pref: '山梨県',
    servant: 'ポール・<br>バニヤン',
    cv: '小見川千明',
    copy: '「キレイで大きい！座るのに、ちょうどいいね」',
    spot: '逆さ富士',
    illust: 'リヨ',
    media: '5/4 山梨日日新聞',
    hash: 'iv1zy1h4',
    update: '2020/5/4',
    position: [-200, -100],
  },
  {
    id: 'nagano',
    pref: '長野県',
    servant: 'キングプロテア',
    cv: '潘めぐみ',
    copy: '「ふわふわで・・・・とても落ち着きます・・・・」',
    spot: '槍ヶ岳と雲海',
    illust: 'ワダアルコ',
    media: '5/4 信濃毎日新聞',
    hash: 'cna82o5v',
    update: '2020/5/4',
    position: [-300, -100],
  },
  {
    id: 'shizuoka',
    pref: '静岡県',
    servant: '葛飾北斎',
    cv: 'ゆかな',
    copy: '「こっからってのはとと様も描いてねぇだろぉ？」',
    spot: '富士山南麓',
    illust: '黒星紅白',
    media: '5/4 静岡新聞',
    hash: '6f1aw4vi',
    update: '2020/5/4',
    position: [-400, -100],
  },
  {
    id: 'niigata',
    pref: '新潟県',
    servant: '風魔小太郎',
    cv: '花江夏樹',
    copy: '「さあ行きますよ、主殿（マスター）！滑走（パラレルターン）！」',
    spot: '苗場スキー場',
    illust: '佐々木少年',
    media: '5/25 新潟日報',
    hash: 'p582tr3s',
    update: '2020/5/25',
    position: [-500, -100],
  },
  {
    id: 'toyama',
    pref: '富山県',
    servant: 'スカサハ＝<br>スカディ',
    cv: '能登麻美子',
    copy: '「良い。実に壮観だ。これが自然だけの力とは、見入ってしまうな？」',
    spot: '雪の大谷',
    illust: 'こやまひろかず（TYPE-MOON）',
    media: '5/25 北日本新聞',
    hash: 'y3jprc5i',
    update: '2020/5/25',
    position: [0, -200],
  },
  {
    id: 'ishikawa',
    pref: '石川県',
    servant: '紅閻魔',
    cv: '久野美咲',
    copy: '「あと、ちょっとだけ。夕紅（ゆうべに）を一緒にみるのでち」',
    spot: '白米千枚田',
    illust: '原田たけひと',
    media: '5/25 北國新聞',
    hash: 'u3wf8mvj',
    update: '2020/5/25',
    position: [-100, -200],
  },
  {
    id: 'fukui',
    pref: '福井県',
    servant: '虞美人',
    cv: '伊瀬茉莉也',
    copy: '「このあと？鯖江にいくわ。項羽様とペアメガネよ」',
    spot: '東尋坊',
    illust: 'toi8',
    media: '5/25 福井新聞',
    hash: 'h8p2nmya',
    update: '2020/5/25',
    position: [-200, -200],
  },
  {
    id: 'gifu',
    pref: '岐阜県',
    servant: 'シャーロック・ホームズ',
    cv: '水島大宙',
    copy: '「合掌か。この国では祈り、という意味もあるらしいね？」',
    spot: '白川郷',
    illust: '山中虎鉄',
    media: '5/25 岐阜新聞',
    hash: 'z987qyuc',
    update: '2020/5/25',
    position: [-300, -200],
  },
  {
    id: 'aichi',
    pref: '愛知県',
    servant: '森長可',
    cv: '谷山紀章',
    copy: '「いつ見ても花火はいいねェ！咲き散りやがれェ！！」',
    spot: '手筒花火',
    illust: 'Dd',
    media: '5/25 中日新聞',
    hash: 'w6k2uqsi',
    update: '2020/5/25',
    position: [-400, -200],
  },
  {
    id: 'mie',
    pref: '三重県',
    servant: 'メドゥーサ',
    cv: '浅川悠',
    copy: '「そうだ。いつか、姉様たちと」',
    spot: '熊野古道',
    illust: 'BLACK（TYPE-MOON）',
    media: '7/20 中日新聞',
    hash: 'u2h4ngmj',
    update: '2020/7/20',
    position: [-600, -500],
  },
  {
    id: 'shiga',
    pref: '滋賀県',
    servant: '鈴鹿御前',
    cv: '東山奈央',
    copy:
      '「ここからの琵琶湖もマジ最高っしょ。ほらマスター、はやく一緒に撮るし！」',
    spot: '満月寺',
    illust: 'たけのこ星人',
    media: '7/20 京都新聞（滋賀県民版）',
    hash: 'g6574qny',
    update: '2020/7/20',
    position: [0, -600],
  },
  {
    id: 'kyoto',
    pref: '京都府',
    servant: '酒呑童子',
    cv: '悠木碧',
    copy: '「飲み足りひんなぁ」',
    spot: '小径',
    illust: '本庄雷太',
    media: '7/20 京都新聞（京都府内版）',
    hash: 'y8nebhik',
    update: '2020/7/20',
    position: [-100, -600],
  },
  {
    id: 'osaka',
    pref: '大阪府',
    servant: 'カルナ＆アルジュナ',
    cv: '遊佐浩二＆島﨑信長',
    copy:
      '「お好み焼きを食べるぞ、マスター」<br>「待ちなさい。今夜は串カツと決めた筈です」',
    spot: '通天閣',
    illust: 'pako',
    media: '7/20 朝日新聞・産経新聞（近畿地方）',
    hash: 'm3pj5yea',
    update: '2020/7/20',
    position: [-200, -600],
  },
  {
    id: 'hyogo',
    pref: '兵庫県',
    servant: '刑部姫',
    cv: '福圓美里',
    copy: '「たまには外も楽しいかも。マーちゃんがいればね♪」',
    spot: '白鷺城',
    illust: '森山大輔',
    media: '7/20 神戸新聞',
    hash: 'c6zgtihx',
    update: '2020/7/20',
    position: [-300, -600],
  },
  {
    id: 'nara',
    pref: '奈良県',
    servant: '柳生但馬守<br>宗矩',
    cv: '山路和弘',
    copy: '「我が心は、不動」',
    spot: '長谷寺本堂',
    illust: '古海鐘一',
    media: '7/20 奈良新聞',
    hash: 'r8mqtiwy',
    update: '2020/7/20',
    position: [-400, -600],
  },
  {
    id: 'wakayama',
    pref: '和歌山県',
    servant: '清姫',
    cv: '種田梨沙',
    copy: '「またかくれんぼで遊びますか？ますたぁ？」',
    spot: '道成寺',
    illust: 'BLACK（TYPE-MOON）',
    media: '7/20 朝日新聞・産経新聞（和歌山県版）',
    hash: 'k823t6nz',
    update: '2020/7/20',
    position: [-500, -600],
  },
  {
    id: 'tottori',
    pref: '鳥取県',
    servant: 'ニトクリス',
    cv: '田中美海',
    copy: '「もう夜が明けます。メジェド様と共に、歩きませい！」',
    spot: '鳥取砂丘',
    illust: '縞うどん（TYPE-MOON）',
    media: '7/6 日本海新聞',
    hash: 'g9sewnx5',
    update: '2020/7/6',
    position: [-200, -500],
  },
  {
    id: 'shimane',
    pref: '島根県',
    servant: 'クー・フーリン[オルタ]',
    cv: '神奈延年',
    copy: '「浮かれてる、だと？刺されてぇのか」',
    spot: '通天橋',
    illust: 'しまどりる',
    media: '7/6 山陰中央新報',
    hash: 'p6zqh5wt',
    update: '2020/7/6',
    position: [-300, -500],
  },
  {
    id: 'okayama',
    pref: '岡山県',
    servant: '紫式部',
    cv: '茅野愛衣',
    copy: '「うふふっ、物語がはじまりそうな場所ですね」',
    spot: '倉敷美観地区',
    illust: '本庄雷太',
    media: '7/6 山陽新聞',
    hash: 'p4tmsb3c',
    update: '2020/7/6',
    position: [-400, -500],
  },
  {
    id: 'hiroshima',
    pref: '広島県',
    servant: '蘭陵王',
    cv: '森なな子',
    copy: '「あぁ、素晴らしい場所ですね。マスター、次はどこにいきましょうか」',
    spot: '紅葉谷公園',
    illust: 'hou',
    media: '7/6 中国新聞',
    hash: 'm9igpr3b',
    update: '2020/7/6',
    position: [-500, -500],
  },
  {
    id: 'yamaguchi',
    pref: '山口県',
    servant: '佐々木小次郎',
    cv: '三木眞一郎',
    copy: '「いやはや絶景かな。うむ、今回は気長に待つとしよう」',
    spot: '巌流島',
    illust: 'また',
    media: '7/6 山口新聞',
    hash: 'q5tu2ezb',
    update: '2020/7/6',
    position: [-600, 0],
  },
  {
    id: 'tokushima',
    pref: '徳島県',
    servant: 'アタランテ',
    cv: '早見沙織',
    copy: '「遅いぞ、マスター。下りも競争するか？」',
    spot: '剣山',
    illust: '輪くすさが',
    media: '7/6 徳島新聞',
    hash: 'i5zpnwhj',
    update: '2020/7/6',
    position: [-600, -100],
  },
  {
    id: 'kagawa',
    pref: '香川県',
    servant: '宮本武蔵',
    cv: '佐倉綾音',
    copy: '「む、閃いた！今日中にうどん100杯目指しちゃおっか！」',
    spot: '道の駅 小豆島オリーブ公園',
    illust: 'こやまひろかず（TYPE-MOON）',
    media: '7/6 四国新聞',
    hash: 'j3a4gh9v',
    update: '2020/7/6',
    position: [-600, -200],
  },
  {
    id: 'ehime',
    pref: '愛媛県',
    servant: 'ジャガーマン',
    cv: '伊藤美紀',
    copy: '「え、デジャヴ？気のせいだニャ！ぷは！」',
    spot: '道後温泉本館',
    illust: '蒼月タカオ（TYPE-MOON）',
    media: '7/6 愛媛新聞',
    hash: 'h3qmx7jv',
    update: '2020/7/6',
    position: [-600, -300],
  },
  {
    id: 'kochi',
    pref: '高知県',
    servant: '岡田以蔵',
    cv: '吉野裕行',
    copy: '「時代は変わるちゅうても、ここは変わらんのう」',
    spot: '桂浜',
    illust: 'lack',
    media: '7/6 高知新聞',
    hash: 'm6hj9w8r',
    update: '2020/7/6',
    position: [-600, -400],
  },
  {
    id: 'fukuoka',
    pref: '福岡県',
    servant: '謎のヒロインX',
    cv: '川澄綾子',
    copy: '「絶品でした！マスター、もう一杯いきましょう！」',
    spot: '中洲屋台街',
    illust: 'BUNBUN',
    media: '6/3 西日本新聞',
    hash: 'f7z9tqkr',
    update: '2020/6/3',
    position: [-500, -200],
  },
  {
    id: 'saga',
    pref: '佐賀県',
    servant: 'イシュタル',
    cv: '植田佳奈',
    copy: '「そうね！この景色、ひとりじめはもったいないもの！」',
    spot: '嘉瀬川河川敷',
    illust: '森井しづき',
    media: '6/3 佐賀新聞',
    hash: 'a4y58gn7',
    update: '2020/6/3',
    position: [0, -300],
  },
  {
    id: 'nagasaki',
    pref: '長崎県',
    servant: 'マリー・アントワネット',
    cv: '種田梨沙',
    copy: '「さぁ、咲き誇りましょう！ヴィヴ・ラ・フランス！」',
    spot: 'ハウステンボス',
    illust: 'ギンカ',
    media: '6/3 長崎新聞',
    hash: 's27hmtyp',
    update: '2020/6/3',
    position: [-100, -300],
  },
  {
    id: 'kumamoto',
    pref: '熊本県',
    servant: '天草四郎',
    cv: '内山昂輝',
    copy: '「心地よい熱さです。信仰はこのような場所でこそ篤くなりましょう」',
    spot: '阿蘇カルデラ',
    illust: '近衛乙嗣',
    media: '6/3 熊本日日新聞',
    hash: 'q79zyb2t',
    update: '2020/6/3',
    position: [-200, -300],
  },
  {
    id: 'oita',
    pref: '大分県',
    servant: 'フランケンシュタイン',
    cv: '野中藍',
    copy: '「つ……い……た……！ゥ〜♪」',
    spot: '沈堕発電所跡',
    illust: '岡崎武士',
    media: '6/3 大分合同新聞',
    hash: 'y827gbqm',
    update: '2020/6/3',
    position: [-300, -300],
  },
  {
    id: 'miyazaki',
    pref: '宮崎県',
    servant: 'シグルド＆ブリュンヒルデ',
    cv: '津田健次郎＆能登麻美子',
    copy:
      '「ようやくのハネムーンだな、我が愛」<br>「こんな人前で……困ってしまいます……」',
    spot: '都井岬',
    illust: '三輪士郎',
    media: '6/3 宮崎日日新聞',
    hash: 'f2qcmwrh',
    update: '2020/6/3',
    position: [-400, -300],
  },
  {
    id: 'kagoshima',
    pref: '鹿児島県',
    servant: 'ヘラクレス',
    cv: '西前忠久',
    copy: '「■■ー！■■■■■ーーー！!！」',
    spot: '屋久島',
    illust: 'Azusa',
    media: '6/3 南日本新聞',
    hash: 'r5jdn9xv',
    update: '2020/6/3',
    position: [-500, -300],
  },
  {
    id: 'okinawa',
    pref: '沖縄県',
    servant: 'マルタ',
    cv: '早見沙織',
    copy: '「ハッハッ...ハレルヤ！ハッハッ...ハレルヤ！」',
    spot: '石垣島',
    illust: '坂本みねぢ',
    media: '6/3 沖縄タイムス、琉球新報',
    hash: 'g9y3tjq4',
    update: '2020/6/3',
    position: [0, -400],
  },
];
const BASE_URL = 'https://5th.fate-go.jp';
const BASE_PATH = './fgo/';
const imgs = data.reduce((prev, curr) => {
  prev.push(...curr.img.map((img) => `${BASE_URL}${img}.jpg`));
  return prev;
}, [] as string[]);

const voices = data.reduce((prev, curr) => {
  prev.push(...curr.voice.map((voice) => `${BASE_URL}${voice}`));
  return prev;
}, [] as string[]);

const archiveImgs = archiveData.reduce((prev, curr) => {
  prev.push(
    `${BASE_URL}/assets/img/archive/ph/fullsize/${curr.id}_${curr.hash}.jpg`
  );
  return prev;
}, [] as string[]);
let id = 0;
const un_finish = [40, 45];
const getId = () => id++;
const download = async () => {
  const fileNames = [];
  for await (const dirEntry of Deno.readDir(`${BASE_PATH}archive`)) {
    fileNames.push(dirEntry.name);
  }

  for (let imgData of archiveData) {
    const img = `${BASE_URL}/assets/img/archive/ph/fullsize/${imgData.id}_${imgData.hash}.jpg`;
    const id = getId();
    const oldName = `${imgData.id}.jpg`;
    const imgName = imgData.servant.replace('<br>', '') + '.jpg';
    if (fileNames.includes(imgName)) continue;
    if (fileNames.includes(oldName)) {
      Deno.rename(
        `${BASE_PATH}archive/${oldName}`,
        `${BASE_PATH}archive/${imgName}`
      );
      continue;
    }
    // if (!un_finish.includes(id)) continue;
    console.log(`开始下载：${img}...`);
    fetch(img).then(async (res) => {
      Deno.writeFile(
        `${BASE_PATH}archive/${imgName}`,
        new Uint8Array(await res.arrayBuffer())
      );
      console.log(`${imgName} 下载完成！`);
    });
  }
};

const downloadVoice = async (limit = Infinity) => {
  const _bashPath = `${BASE_PATH}/voices/`;
  const fileNames: string[] = [];
  for await (const dirEntry of Deno.readDir(_bashPath)) {
    fileNames.push(dirEntry.name);
  }

  const promiseList = voices
    .slice(0, limit)
    .filter((path) => {
      const fileName = path.split('/').pop()!;
      return !fileNames.includes(fileName);
    })
    .map((path) => {
      const fileName = path.split('/').pop()!;

      console.log(`开始下载：${path}...`);

      return fetch(path).then(async (res) => {
        Deno.writeFile(
          `${_bashPath}${fileName}`,
          new Uint8Array(await res.arrayBuffer())
        );
        console.log(`${fileName} 下载完成！`);
      });
    });
  Promise.all(promiseList).then(() => console.log('任务完成！'));
};

download();
